#ifndef _SOUND_H_
#define _SOUND_H_

#include <Windows.h>

typedef enum
{
	SOUND_LABEL_BGM000 ,		
	SOUND_LABEL_STARTBGM,
	SOUND_LABER_ENDBGM,
	SOUND_LABER_VICTORYBGM,
	SOUND_LABER_BOSSBGM,
	SOUND_LABEL_SE_SHOT,		
	SOUND_LABEL_SE_EXPLOSION,	
	SOUND_LABEL_SE_ITEM,
	SOUND_LABEL_SE_BAKUHATU,
	SOUND_LABEL_SE_Ult_Create,
	SOUND_LABEL_SE_Bullet_Enemy,
	SOUND_LABEL_SE_Buss_Bullet_Player,
	SOUND_LABEL_SE_Enemy_Bullet_Player,
	SOUND_LABEL_SE_BOSS_DISTROY,
	SOUND_LABEL_SE_ENEMY_3_DISTROY,
	SOUND_LABEL_SE_PLAYER_DISTROY,
	SOUND_LABEL_SE_MISSILE,
	SOUND_LABEL_SE_CHOICE,
	SOUND_LABEL_SE_AUTO_BULLET_SHOT,
	SOUND_LABEL_SE_AUTO_BULLET_DISTORY,
	SOUND_LABEL_SE_BOSS_SKILL,
	SOUND_LABEL_SE_BOSS_BULLET,
	SOUND_LABEL_SE_ENEMY_DIS,


	SOUND_LABEL_MAX,
} SOUND_LABEL;

HRESULT InitSound(HWND hWnd);
void UninitSound(void);
HRESULT PlaySound(SOUND_LABEL label);
void StopSound(SOUND_LABEL label);
void StopSound(void);

#endif
